# Generated by Django 5.0.1 on 2025-12-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='issues/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='journals/'),
        ),
    ]
